[package]
name = "memory-pager"
version = "0.3.0"
license = "Apache-2.0"
repository = "https://github.com/datrs/memory-pager"
documentation = "https://docs.rs/memory-pager"
description = "Access memory using small fixed size buffers"
authors = ["datrs <yoshuawuyts@gmail.com>"]

[dependencies]

[dev-dependencies]
# clippy = "0.0.189"
